#coding:utf-8

DEFAULT_PADDING = 'SAME'
ALL_PADDINT = ('SAME', 'VALID')

DEFAULT_INITMODE = "X"
ALL_INIT = ("X","N")

DEFAULT_REGULAR = "L2"
ALL_REGULAR = ('L2', 'L1', "None")

DEFAULT_WEIGHT_DECAY = 0.0002


DEFAULT_RNN_CELL_STYLE = "GRU"
ALL_LSTM_STYLE=("LSTM","GRU") #目前只实现LSTM 后期会对GRU进行扩展  单纯的RNN不打算进行实现

DEFAULT_RNN_KEEP_PROB = 1.0


DEFAULT_BN_MOVING_DECAY = 0.997
DEFAULT_BN_EPSILON = 0.00001